using MultiSessionHost.Core.Models;

namespace MultiSessionHost.Desktop.Observability;

public enum SessionObservabilityStatus
{
    Unknown = 0,
    Healthy = 1,
    Degraded = 2,
    Faulted = 3,
    Paused = 4,
    Idle = 5,
    Recovering = 6
}

public enum SessionObservabilitySeverity
{
    Trace = 0,
    Debug = 1,
    Information = 2,
    Warning = 3,
    Error = 4,
    Critical = 5
}

public enum SessionObservabilityOutcome
{
    Unknown = 0,
    Success = 1,
    Failure = 2,
    Skipped = 3,
    Deferred = 4,
    Blocked = 5,
    Aborted = 6,
    Withdrawn = 7,
    Hidden = 8,
    Waiting = 9,
    Paused = 10
}

public enum SessionObservabilityCategory
{
    Snapshot = 0,
    Extraction = 1,
    Domain = 2,
    Policy = 3,
    Execution = 4,
    Command = 5,
    Persistence = 6,
    Attachment = 7,
    Adapter = 8,
    Lifecycle = 9,
    Recovery = 10,
    Activity = 11,
    Memory = 12
}

public abstract record SessionObservabilityEvent(
    SessionId SessionId,
    Guid EventId,
    string EventType,
    string Category,
    DateTimeOffset OccurredAtUtc,
    double? DurationMs,
    string Outcome,
    SessionObservabilitySeverity Severity,
    string? ReasonCode,
    string? Reason,
    string? SourceComponent,
    string? CorrelationId,
    string? TraceId,
    IReadOnlyDictionary<string, string> Metadata);

public sealed record SessionLatencyMeasurement(
    SessionId SessionId,
    Guid EventId,
    string Stage,
    string Category,
    DateTimeOffset OccurredAtUtc,
    double? DurationMs,
    string Outcome,
    string? ReasonCode,
    string? Reason,
    string? SourceComponent,
    string? CorrelationId,
    string? TraceId,
    IReadOnlyDictionary<string, string> Metadata) : SessionObservabilityEvent(
        SessionId,
        EventId,
        Stage,
        Category,
        OccurredAtUtc,
        DurationMs,
        Outcome,
        SessionObservabilitySeverity.Information,
        ReasonCode,
        Reason,
        SourceComponent,
        CorrelationId,
        TraceId,
        Metadata);

public sealed record SessionReasonMetric(
    SessionId SessionId,
    string Category,
    string ReasonCode,
    string? Reason,
    long Count,
    DateTimeOffset LastOccurredAtUtc,
    string? SourceComponent);

public sealed record AdapterErrorRecord(
    SessionId SessionId,
    Guid EventId,
    DateTimeOffset OccurredAtUtc,
    string AdapterName,
    string Operation,
    string ExceptionType,
    string Message,
    string? ReasonCode,
    string? SourceComponent,
    string? CorrelationId,
    string? TraceId,
    IReadOnlyDictionary<string, string> Metadata) : SessionObservabilityEvent(
        SessionId,
        EventId,
        "adapter.error",
        SessionObservabilityCategory.Adapter.ToString(),
        OccurredAtUtc,
        null,
        SessionObservabilityOutcome.Failure.ToString(),
        SessionObservabilitySeverity.Error,
        ReasonCode,
        Message,
        SourceComponent,
        CorrelationId,
        TraceId,
        Metadata);

public sealed record AttachmentLifecycleEvent(
    SessionId SessionId,
    Guid EventId,
    DateTimeOffset OccurredAtUtc,
    string Operation,
    string AdapterName,
    string? TargetKind,
    string Outcome,
    double? DurationMs,
    string? ReasonCode,
    string? Reason,
    string? SourceComponent,
    string? CorrelationId,
    string? TraceId,
    IReadOnlyDictionary<string, string> Metadata) : SessionObservabilityEvent(
        SessionId,
        EventId,
        $"attachment.{Operation}",
        SessionObservabilityCategory.Attachment.ToString(),
        OccurredAtUtc,
        DurationMs,
        Outcome,
        SessionObservabilitySeverity.Information,
        ReasonCode,
        Reason,
        SourceComponent,
        CorrelationId,
        TraceId,
        Metadata);

public sealed record PersistenceLifecycleEvent(
    SessionId SessionId,
    Guid EventId,
    DateTimeOffset OccurredAtUtc,
    string Operation,
    string Outcome,
    double? DurationMs,
    string? Path,
    int? ItemCount,
    string? ReasonCode,
    string? Reason,
    string? SourceComponent,
    string? CorrelationId,
    string? TraceId,
    IReadOnlyDictionary<string, string> Metadata) : SessionObservabilityEvent(
        SessionId,
        EventId,
        $"persistence.{Operation}",
        SessionObservabilityCategory.Persistence.ToString(),
        OccurredAtUtc,
        DurationMs,
        Outcome,
        SessionObservabilitySeverity.Information,
        ReasonCode,
        Reason,
        SourceComponent,
        CorrelationId,
        TraceId,
        Metadata);

public sealed record PolicyEvaluationEvent(
    SessionId SessionId,
    Guid EventId,
    DateTimeOffset OccurredAtUtc,
    string PolicyName,
    string Outcome,
    double? DurationMs,
    int DirectiveCount,
    int PolicyCount,
    bool MemoryInfluenced,
    bool WasPolicyPaused,
    string? ReasonCode,
    string? Reason,
    string? SourceComponent,
    string? CorrelationId,
    string? TraceId,
    IReadOnlyDictionary<string, string> Metadata) : SessionObservabilityEvent(
        SessionId,
        EventId,
        $"policy.{PolicyName}",
        SessionObservabilityCategory.Policy.ToString(),
        OccurredAtUtc,
        DurationMs,
        Outcome,
        SessionObservabilitySeverity.Information,
        ReasonCode,
        Reason,
        SourceComponent,
        CorrelationId,
        TraceId,
        Metadata);

public sealed record DecisionExecutionEvent(
    SessionId SessionId,
    Guid EventId,
    DateTimeOffset OccurredAtUtc,
    string PlanFingerprint,
    string ExecutionStatus,
    double? DurationMs,
    bool WasAutoExecuted,
    int DirectiveCount,
    int SucceededDirectiveCount,
    int FailedDirectiveCount,
    int SkippedDirectiveCount,
    int DeferredDirectiveCount,
    int BlockedDirectiveCount,
    int AbortedDirectiveCount,
    string? ReasonCode,
    string? Reason,
    string? SourceComponent,
    string? CorrelationId,
    string? TraceId,
    IReadOnlyDictionary<string, string> Metadata) : SessionObservabilityEvent(
        SessionId,
        EventId,
        "decision.execution",
        SessionObservabilityCategory.Execution.ToString(),
        OccurredAtUtc,
        DurationMs,
        ExecutionStatus,
        SessionObservabilitySeverity.Information,
        ReasonCode,
        Reason,
        SourceComponent,
        CorrelationId,
        TraceId,
        Metadata);

public sealed record CommandExecutionEvent(
    SessionId SessionId,
    Guid EventId,
    DateTimeOffset OccurredAtUtc,
    string CommandKind,
    string? NodeId,
    string? AdapterName,
    string Outcome,
    double? DurationMs,
    string? ReasonCode,
    string? Reason,
    string? SourceComponent,
    string? CorrelationId,
    string? TraceId,
    IReadOnlyDictionary<string, string> Metadata) : SessionObservabilityEvent(
        SessionId,
        EventId,
        "command.execution",
        SessionObservabilityCategory.Command.ToString(),
        OccurredAtUtc,
        DurationMs,
        Outcome,
        SessionObservabilitySeverity.Information,
        ReasonCode,
        Reason,
        SourceComponent,
        CorrelationId,
        TraceId,
        Metadata);

public sealed record SessionObservabilitySummary(
    SessionId SessionId,
    DateTimeOffset LastUpdatedAtUtc,
    SessionObservabilityStatus Status,
    long SnapshotCount,
    long ExtractionCount,
    long DomainProjectionCount,
    long PolicyEvaluationCount,
    long DecisionExecutionCount,
    long CommandExecutionCount,
    long PersistenceFlushCount,
    long PersistenceRehydrateCount,
    long AttachCount,
    long ReattachCount,
    long AdapterErrorCount,
    long WithdrawCount,
    long AbortCount,
    long HideCount,
    long WaitCount,
    long SkippedExecutionCount,
    long CommandFailureCount,
    long PersistenceFailureCount,
    long RecentWarningCount,
    long RecentErrorCount,
    double? LastSnapshotDurationMs,
    double? LastExtractionDurationMs,
    double? LastPolicyEvaluationDurationMs,
    double? LastDecisionExecutionDurationMs,
    double? LastCommandDurationMs,
    double? LastPersistenceFlushDurationMs,
    double? LastPersistenceRehydrateDurationMs,
    double? LastAttachDurationMs,
    double? LastReattachDurationMs,
    string? LastSnapshotOutcome,
    string? LastExtractionOutcome,
    string? LastPolicyOutcome,
    string? LastDecisionOutcome,
    string? LastCommandOutcome,
    string? LastPersistenceOutcome,
    string? LastRehydrateOutcome,
    string? LastAttachOutcome,
    string? LastReattachOutcome,
    string? LastAdapterError,
    string? LastPersistenceError,
    string? LastReasonCode,
    string? LastReason,
    IReadOnlyDictionary<string, long> ReasonCounts)
{
    public static SessionObservabilitySummary Create(SessionId sessionId, DateTimeOffset now) =>
        new(
            sessionId,
            now,
            SessionObservabilityStatus.Unknown,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            new Dictionary<string, long>(StringComparer.OrdinalIgnoreCase));
}

public sealed record SessionObservabilityMetricsSnapshot(
    SessionId SessionId,
    DateTimeOffset CapturedAtUtc,
    SessionObservabilitySummary Summary,
    IReadOnlyList<SessionLatencyMeasurement> RecentLatencies,
    IReadOnlyList<SessionReasonMetric> ReasonMetrics,
    IReadOnlyList<AdapterErrorRecord> RecentErrors);

public sealed record SessionObservabilitySnapshot(
    SessionObservabilitySummary Summary,
    IReadOnlyList<SessionObservabilityEvent> RecentEvents,
    SessionObservabilityMetricsSnapshot Metrics,
    IReadOnlyList<AdapterErrorRecord> RecentErrors);

public sealed record GlobalObservabilitySnapshot(
    DateTimeOffset CapturedAtUtc,
    SessionObservabilityStatus Status,
    int ActiveSessions,
    int FaultedSessions,
    int PausedSessions,
    long TotalEvents,
    long TotalErrors,
    IReadOnlyList<SessionObservabilitySummary> Sessions,
    IReadOnlyList<AdapterErrorRecord> RecentErrors);