using MultiSessionHost.Core.Enums;

namespace MultiSessionHost.Desktop.Policy;

public abstract record PolicyRuleCandidate(
    string CandidateId,
    string? Label,
    string? Type,
    IReadOnlyList<string> Tags,
    ThreatSeverity ThreatSeverity,
    RiskSeverity RiskSeverity,
    RiskPolicySuggestion SuggestedPolicy,
    SessionStatus SessionStatus,
    NavigationStatus NavigationStatus,
    bool IsTransitioning,
    bool HasDestination,
    bool IsNavigationIdle,
    bool IsActivityIdle,
    bool HasActiveTarget,
    bool ResourceCritical,
    bool ResourceDegraded,
    bool DefensivePostureActive,
    double? ProgressPercent,
    double? ResourcePercent,
    int? WarningCount,
    int? UnknownCount,
    int? AvailableCount,
    double? Confidence,
    IReadOnlyDictionary<string, double> Metrics,
    IReadOnlyDictionary<string, string> Metadata);

public sealed record SiteSelectionCandidate(
    string CandidateId,
    string? Label,
    string? Type,
    IReadOnlyList<string> Tags,
    ThreatSeverity ThreatSeverity,
    RiskSeverity RiskSeverity,
    RiskPolicySuggestion SuggestedPolicy,
    SessionStatus SessionStatus,
    NavigationStatus NavigationStatus,
    bool IsTransitioning,
    bool HasDestination,
    bool IsNavigationIdle,
    bool IsActivityIdle,
    bool HasActiveTarget,
    bool ResourceCritical,
    bool ResourceDegraded,
    bool DefensivePostureActive,
    double? ProgressPercent,
    double? ResourcePercent,
    int? WarningCount,
    int? UnknownCount,
    int? AvailableCount,
    double? Confidence,
    IReadOnlyDictionary<string, double> Metrics,
    IReadOnlyDictionary<string, string> Metadata) : PolicyRuleCandidate(CandidateId, Label, Type, Tags, ThreatSeverity, RiskSeverity, SuggestedPolicy, SessionStatus, NavigationStatus, IsTransitioning, HasDestination, IsNavigationIdle, IsActivityIdle, HasActiveTarget, ResourceCritical, ResourceDegraded, DefensivePostureActive, ProgressPercent, ResourcePercent, WarningCount, UnknownCount, AvailableCount, Confidence, Metrics, Metadata);

public sealed record ThreatResponseCandidate(
    string CandidateId,
    string? Label,
    string? Type,
    IReadOnlyList<string> Tags,
    ThreatSeverity ThreatSeverity,
    RiskSeverity RiskSeverity,
    RiskPolicySuggestion SuggestedPolicy,
    SessionStatus SessionStatus,
    NavigationStatus NavigationStatus,
    bool IsTransitioning,
    bool HasDestination,
    bool IsNavigationIdle,
    bool IsActivityIdle,
    bool HasActiveTarget,
    bool ResourceCritical,
    bool ResourceDegraded,
    bool DefensivePostureActive,
    double? ProgressPercent,
    double? ResourcePercent,
    int? WarningCount,
    int? UnknownCount,
    int? AvailableCount,
    double? Confidence,
    IReadOnlyDictionary<string, double> Metrics,
    IReadOnlyDictionary<string, string> Metadata) : PolicyRuleCandidate(CandidateId, Label, Type, Tags, ThreatSeverity, RiskSeverity, SuggestedPolicy, SessionStatus, NavigationStatus, IsTransitioning, HasDestination, IsNavigationIdle, IsActivityIdle, HasActiveTarget, ResourceCritical, ResourceDegraded, DefensivePostureActive, ProgressPercent, ResourcePercent, WarningCount, UnknownCount, AvailableCount, Confidence, Metrics, Metadata);

public sealed record TargetPriorityCandidate(
    string CandidateId,
    string? Label,
    string? Type,
    IReadOnlyList<string> Tags,
    ThreatSeverity ThreatSeverity,
    RiskSeverity RiskSeverity,
    RiskPolicySuggestion SuggestedPolicy,
    SessionStatus SessionStatus,
    NavigationStatus NavigationStatus,
    bool IsTransitioning,
    bool HasDestination,
    bool IsNavigationIdle,
    bool IsActivityIdle,
    bool HasActiveTarget,
    bool ResourceCritical,
    bool ResourceDegraded,
    bool DefensivePostureActive,
    double? ProgressPercent,
    double? ResourcePercent,
    int? WarningCount,
    int? UnknownCount,
    int? AvailableCount,
    double? Confidence,
    IReadOnlyDictionary<string, double> Metrics,
    IReadOnlyDictionary<string, string> Metadata) : PolicyRuleCandidate(CandidateId, Label, Type, Tags, ThreatSeverity, RiskSeverity, SuggestedPolicy, SessionStatus, NavigationStatus, IsTransitioning, HasDestination, IsNavigationIdle, IsActivityIdle, HasActiveTarget, ResourceCritical, ResourceDegraded, DefensivePostureActive, ProgressPercent, ResourcePercent, WarningCount, UnknownCount, AvailableCount, Confidence, Metrics, Metadata);

public sealed record ResourceUsageCandidate(
    string CandidateId,
    string? Label,
    string? Type,
    IReadOnlyList<string> Tags,
    ThreatSeverity ThreatSeverity,
    RiskSeverity RiskSeverity,
    RiskPolicySuggestion SuggestedPolicy,
    SessionStatus SessionStatus,
    NavigationStatus NavigationStatus,
    bool IsTransitioning,
    bool HasDestination,
    bool IsNavigationIdle,
    bool IsActivityIdle,
    bool HasActiveTarget,
    bool ResourceCritical,
    bool ResourceDegraded,
    bool DefensivePostureActive,
    double? ProgressPercent,
    double? ResourcePercent,
    int? WarningCount,
    int? UnknownCount,
    int? AvailableCount,
    double? Confidence,
    IReadOnlyDictionary<string, double> Metrics,
    IReadOnlyDictionary<string, string> Metadata) : PolicyRuleCandidate(CandidateId, Label, Type, Tags, ThreatSeverity, RiskSeverity, SuggestedPolicy, SessionStatus, NavigationStatus, IsTransitioning, HasDestination, IsNavigationIdle, IsActivityIdle, HasActiveTarget, ResourceCritical, ResourceDegraded, DefensivePostureActive, ProgressPercent, ResourcePercent, WarningCount, UnknownCount, AvailableCount, Confidence, Metrics, Metadata);

public sealed record TransitCandidate(
    string CandidateId,
    string? Label,
    string? Type,
    IReadOnlyList<string> Tags,
    ThreatSeverity ThreatSeverity,
    RiskSeverity RiskSeverity,
    RiskPolicySuggestion SuggestedPolicy,
    SessionStatus SessionStatus,
    NavigationStatus NavigationStatus,
    bool IsTransitioning,
    bool HasDestination,
    bool IsNavigationIdle,
    bool IsActivityIdle,
    bool HasActiveTarget,
    bool ResourceCritical,
    bool ResourceDegraded,
    bool DefensivePostureActive,
    double? ProgressPercent,
    double? ResourcePercent,
    int? WarningCount,
    int? UnknownCount,
    int? AvailableCount,
    double? Confidence,
    IReadOnlyDictionary<string, double> Metrics,
    IReadOnlyDictionary<string, string> Metadata) : PolicyRuleCandidate(CandidateId, Label, Type, Tags, ThreatSeverity, RiskSeverity, SuggestedPolicy, SessionStatus, NavigationStatus, IsTransitioning, HasDestination, IsNavigationIdle, IsActivityIdle, HasActiveTarget, ResourceCritical, ResourceDegraded, DefensivePostureActive, ProgressPercent, ResourcePercent, WarningCount, UnknownCount, AvailableCount, Confidence, Metrics, Metadata);

public sealed record AbortCandidate(
    string CandidateId,
    string? Label,
    string? Type,
    IReadOnlyList<string> Tags,
    ThreatSeverity ThreatSeverity,
    RiskSeverity RiskSeverity,
    RiskPolicySuggestion SuggestedPolicy,
    SessionStatus SessionStatus,
    NavigationStatus NavigationStatus,
    bool IsTransitioning,
    bool HasDestination,
    bool IsNavigationIdle,
    bool IsActivityIdle,
    bool HasActiveTarget,
    bool ResourceCritical,
    bool ResourceDegraded,
    bool DefensivePostureActive,
    double? ProgressPercent,
    double? ResourcePercent,
    int? WarningCount,
    int? UnknownCount,
    int? AvailableCount,
    double? Confidence,
    IReadOnlyDictionary<string, double> Metrics,
    IReadOnlyDictionary<string, string> Metadata) : PolicyRuleCandidate(CandidateId, Label, Type, Tags, ThreatSeverity, RiskSeverity, SuggestedPolicy, SessionStatus, NavigationStatus, IsTransitioning, HasDestination, IsNavigationIdle, IsActivityIdle, HasActiveTarget, ResourceCritical, ResourceDegraded, DefensivePostureActive, ProgressPercent, ResourcePercent, WarningCount, UnknownCount, AvailableCount, Confidence, Metrics, Metadata);

public sealed record GenericPolicyRuleCandidate(
    string CandidateId,
    string? Label,
    string? Type,
    IReadOnlyList<string> Tags,
    ThreatSeverity ThreatSeverity,
    RiskSeverity RiskSeverity,
    RiskPolicySuggestion SuggestedPolicy,
    SessionStatus SessionStatus,
    NavigationStatus NavigationStatus,
    bool IsTransitioning,
    bool HasDestination,
    bool IsNavigationIdle,
    bool IsActivityIdle,
    bool HasActiveTarget,
    bool ResourceCritical,
    bool ResourceDegraded,
    bool DefensivePostureActive,
    double? ProgressPercent,
    double? ResourcePercent,
    int? WarningCount,
    int? UnknownCount,
    int? AvailableCount,
    double? Confidence,
    IReadOnlyDictionary<string, double> Metrics,
    IReadOnlyDictionary<string, string> Metadata) : PolicyRuleCandidate(CandidateId, Label, Type, Tags, ThreatSeverity, RiskSeverity, SuggestedPolicy, SessionStatus, NavigationStatus, IsTransitioning, HasDestination, IsNavigationIdle, IsActivityIdle, HasActiveTarget, ResourceCritical, ResourceDegraded, DefensivePostureActive, ProgressPercent, ResourcePercent, WarningCount, UnknownCount, AvailableCount, Confidence, Metrics, Metadata);
