using MultiSessionHost.Core.Enums;

namespace MultiSessionHost.Desktop.Policy;

public enum PolicyRuleFamily
{
    SiteSelection = 0,
    ThreatResponse = 1,
    TargetPrioritization = 2,
    ResourceUsage = 3,
    Transit = 4,
    Abort = 5
}

public sealed record PolicyRuleSet(
    IReadOnlyList<SiteSelectionRule> SiteSelectionAllowRules,
    IReadOnlyList<SiteSelectionRule> SiteSelectionFallbackRules,
    IReadOnlyList<ThreatResponseRule> ThreatResponseRetreatRules,
    IReadOnlyList<ThreatResponseRule> ThreatResponseDenyRules,
    IReadOnlyList<ThreatResponseRule> ThreatResponseFallbackRules,
    IReadOnlyList<TargetPriorityRule> TargetPriorityRules,
    IReadOnlyList<TargetPriorityRule> TargetDenyRules,
    IReadOnlyList<TargetPriorityRule> TargetFallbackRules,
    IReadOnlyList<ResourceUsageRule> ResourceUsageRules,
    IReadOnlyList<ResourceUsageRule> ResourceUsageFallbackRules,
    IReadOnlyList<TransitRule> TransitRules,
    IReadOnlyList<TransitRule> TransitFallbackRules,
    IReadOnlyList<AbortRule> AbortRules,
    IReadOnlyList<AbortRule> AbortFallbackRules)
{
    public IReadOnlyList<SiteSelectionRule> SiteSelectionRules =>
        SiteSelectionAllowRules.Concat(SiteSelectionFallbackRules).ToArray();

    public IReadOnlyList<ThreatResponseRule> ThreatResponseRules =>
        ThreatResponseRetreatRules.Concat(ThreatResponseDenyRules).Concat(ThreatResponseFallbackRules).ToArray();

    public IReadOnlyList<TargetPriorityRule> TargetPrioritizationRules =>
        TargetPriorityRules.Concat(TargetDenyRules).Concat(TargetFallbackRules).ToArray();

    public IReadOnlyList<ResourceUsageRule> AllResourceUsageRules =>
        ResourceUsageRules.Concat(ResourceUsageFallbackRules).ToArray();

    public IReadOnlyList<TransitRule> AllTransitRules =>
        TransitRules.Concat(TransitFallbackRules).ToArray();

    public IReadOnlyList<AbortRule> AllAbortRules =>
        AbortRules.Concat(AbortFallbackRules).ToArray();
}

public abstract record PolicyRule(
    string RuleName,
    PolicyRuleFamily Family,
    IReadOnlyList<string> MatchLabels,
    PolicyRuleMatchMode LabelMatchMode,
    IReadOnlyList<string> MatchTypes,
    PolicyRuleMatchMode TypeMatchMode,
    IReadOnlyList<string> MatchTags,
    bool RequireAllTags,
    IReadOnlyList<ThreatSeverity> AllowedThreatSeverities,
    ThreatSeverity? MinThreatSeverity,
    RiskSeverity? MinRiskSeverity,
    IReadOnlyList<RiskPolicySuggestion> MatchSuggestedPolicies,
    IReadOnlyList<SessionStatus> MatchSessionStatuses,
    IReadOnlyList<NavigationStatus> MatchNavigationStatuses,
    bool? RequireTransitioning,
    bool RequireDestination,
    bool RequireIdleNavigation,
    bool RequireIdleActivity,
    bool RequireNoActiveTarget,
    bool RequireActiveTarget,
    bool? MatchResourceCritical,
    bool? MatchResourceDegraded,
    bool RequireDefensivePosture,
    double? MinProgressPercent,
    double? MaxProgressPercent,
    double? MinResourcePercent,
    double? MaxResourcePercent,
    int? MinWarningCount,
    int? MaxWarningCount,
    int? MinUnknownCount,
    int? MaxUnknownCount,
    int? MinAvailableCount,
    int? MaxAvailableCount,
    double? MinConfidence,
    double? MaxConfidence,
    string? MetricName,
    double? MinMetricValue,
    double? MaxMetricValue,
    DecisionDirectiveKind DirectiveKind,
    int Priority,
    string SuggestedPolicy,
    bool Blocks,
    bool Aborts,
    TimeSpan MinimumWait,
    string? ThresholdName,
    string? PolicyMode,
    string? TargetLabelTemplate,
    string Reason)
{
    public string PolicyName { get; init; } = string.Empty;

    public string RuleFamily { get; init; } = Family.ToString();

    public string RuleIntent { get; init; } = string.Empty;

    public string SourceScope { get; init; } = string.Empty;

    public bool IsFallback { get; init; }
}

public sealed record SiteSelectionRule(
    string RuleName,
    IReadOnlyList<string> MatchLabels,
    PolicyRuleMatchMode LabelMatchMode,
    IReadOnlyList<string> MatchTypes,
    PolicyRuleMatchMode TypeMatchMode,
    IReadOnlyList<string> MatchTags,
    bool RequireAllTags,
    IReadOnlyList<ThreatSeverity> AllowedThreatSeverities,
    ThreatSeverity? MinThreatSeverity,
    RiskSeverity? MinRiskSeverity,
    IReadOnlyList<RiskPolicySuggestion> MatchSuggestedPolicies,
    IReadOnlyList<SessionStatus> MatchSessionStatuses,
    IReadOnlyList<NavigationStatus> MatchNavigationStatuses,
    bool? RequireTransitioning,
    bool RequireDestination,
    bool RequireIdleNavigation,
    bool RequireIdleActivity,
    bool RequireNoActiveTarget,
    bool RequireActiveTarget,
    bool? MatchResourceCritical,
    bool? MatchResourceDegraded,
    bool RequireDefensivePosture,
    double? MinProgressPercent,
    double? MaxProgressPercent,
    double? MinResourcePercent,
    double? MaxResourcePercent,
    int? MinWarningCount,
    int? MaxWarningCount,
    int? MinUnknownCount,
    int? MaxUnknownCount,
    int? MinAvailableCount,
    int? MaxAvailableCount,
    double? MinConfidence,
    double? MaxConfidence,
    string? MetricName,
    double? MinMetricValue,
    double? MaxMetricValue,
    DecisionDirectiveKind DirectiveKind,
    int Priority,
    string SuggestedPolicy,
    bool Blocks,
    bool Aborts,
    TimeSpan MinimumWait,
    string? ThresholdName,
    string? PolicyMode,
    string? TargetLabelTemplate,
    string Reason) : PolicyRule(
        RuleName, PolicyRuleFamily.SiteSelection, MatchLabels, LabelMatchMode, MatchTypes, TypeMatchMode, MatchTags, RequireAllTags,
        AllowedThreatSeverities, MinThreatSeverity, MinRiskSeverity, MatchSuggestedPolicies, MatchSessionStatuses, MatchNavigationStatuses,
        RequireTransitioning, RequireDestination, RequireIdleNavigation, RequireIdleActivity, RequireNoActiveTarget, RequireActiveTarget,
        MatchResourceCritical, MatchResourceDegraded, RequireDefensivePosture, MinProgressPercent, MaxProgressPercent, MinResourcePercent,
        MaxResourcePercent, MinWarningCount, MaxWarningCount, MinUnknownCount, MaxUnknownCount, MinAvailableCount, MaxAvailableCount,
        MinConfidence, MaxConfidence, MetricName, MinMetricValue, MaxMetricValue, DirectiveKind, Priority, SuggestedPolicy, Blocks,
        Aborts, MinimumWait, ThresholdName, PolicyMode, TargetLabelTemplate, Reason);

public sealed record ThreatResponseRule(
    string RuleName,
    IReadOnlyList<string> MatchLabels,
    PolicyRuleMatchMode LabelMatchMode,
    IReadOnlyList<string> MatchTypes,
    PolicyRuleMatchMode TypeMatchMode,
    IReadOnlyList<string> MatchTags,
    bool RequireAllTags,
    IReadOnlyList<ThreatSeverity> AllowedThreatSeverities,
    ThreatSeverity? MinThreatSeverity,
    RiskSeverity? MinRiskSeverity,
    IReadOnlyList<RiskPolicySuggestion> MatchSuggestedPolicies,
    IReadOnlyList<SessionStatus> MatchSessionStatuses,
    IReadOnlyList<NavigationStatus> MatchNavigationStatuses,
    bool? RequireTransitioning,
    bool RequireDestination,
    bool RequireIdleNavigation,
    bool RequireIdleActivity,
    bool RequireNoActiveTarget,
    bool RequireActiveTarget,
    bool? MatchResourceCritical,
    bool? MatchResourceDegraded,
    bool RequireDefensivePosture,
    double? MinProgressPercent,
    double? MaxProgressPercent,
    double? MinResourcePercent,
    double? MaxResourcePercent,
    int? MinWarningCount,
    int? MaxWarningCount,
    int? MinUnknownCount,
    int? MaxUnknownCount,
    int? MinAvailableCount,
    int? MaxAvailableCount,
    double? MinConfidence,
    double? MaxConfidence,
    string? MetricName,
    double? MinMetricValue,
    double? MaxMetricValue,
    DecisionDirectiveKind DirectiveKind,
    int Priority,
    string SuggestedPolicy,
    bool Blocks,
    bool Aborts,
    TimeSpan MinimumWait,
    string? ThresholdName,
    string? PolicyMode,
    string? TargetLabelTemplate,
    string Reason) : PolicyRule(
        RuleName, PolicyRuleFamily.ThreatResponse, MatchLabels, LabelMatchMode, MatchTypes, TypeMatchMode, MatchTags, RequireAllTags,
        AllowedThreatSeverities, MinThreatSeverity, MinRiskSeverity, MatchSuggestedPolicies, MatchSessionStatuses, MatchNavigationStatuses,
        RequireTransitioning, RequireDestination, RequireIdleNavigation, RequireIdleActivity, RequireNoActiveTarget, RequireActiveTarget,
        MatchResourceCritical, MatchResourceDegraded, RequireDefensivePosture, MinProgressPercent, MaxProgressPercent, MinResourcePercent,
        MaxResourcePercent, MinWarningCount, MaxWarningCount, MinUnknownCount, MaxUnknownCount, MinAvailableCount, MaxAvailableCount,
        MinConfidence, MaxConfidence, MetricName, MinMetricValue, MaxMetricValue, DirectiveKind, Priority, SuggestedPolicy, Blocks,
        Aborts, MinimumWait, ThresholdName, PolicyMode, TargetLabelTemplate, Reason);

public sealed record TargetPriorityRule(
    string RuleName,
    IReadOnlyList<string> MatchLabels,
    PolicyRuleMatchMode LabelMatchMode,
    IReadOnlyList<string> MatchTypes,
    PolicyRuleMatchMode TypeMatchMode,
    IReadOnlyList<string> MatchTags,
    bool RequireAllTags,
    IReadOnlyList<ThreatSeverity> AllowedThreatSeverities,
    ThreatSeverity? MinThreatSeverity,
    RiskSeverity? MinRiskSeverity,
    IReadOnlyList<RiskPolicySuggestion> MatchSuggestedPolicies,
    IReadOnlyList<SessionStatus> MatchSessionStatuses,
    IReadOnlyList<NavigationStatus> MatchNavigationStatuses,
    bool? RequireTransitioning,
    bool RequireDestination,
    bool RequireIdleNavigation,
    bool RequireIdleActivity,
    bool RequireNoActiveTarget,
    bool RequireActiveTarget,
    bool? MatchResourceCritical,
    bool? MatchResourceDegraded,
    bool RequireDefensivePosture,
    double? MinProgressPercent,
    double? MaxProgressPercent,
    double? MinResourcePercent,
    double? MaxResourcePercent,
    int? MinWarningCount,
    int? MaxWarningCount,
    int? MinUnknownCount,
    int? MaxUnknownCount,
    int? MinAvailableCount,
    int? MaxAvailableCount,
    double? MinConfidence,
    double? MaxConfidence,
    string? MetricName,
    double? MinMetricValue,
    double? MaxMetricValue,
    DecisionDirectiveKind DirectiveKind,
    int Priority,
    string SuggestedPolicy,
    bool Blocks,
    bool Aborts,
    TimeSpan MinimumWait,
    string? ThresholdName,
    string? PolicyMode,
    string? TargetLabelTemplate,
    string Reason) : PolicyRule(
        RuleName, PolicyRuleFamily.TargetPrioritization, MatchLabels, LabelMatchMode, MatchTypes, TypeMatchMode, MatchTags, RequireAllTags,
        AllowedThreatSeverities, MinThreatSeverity, MinRiskSeverity, MatchSuggestedPolicies, MatchSessionStatuses, MatchNavigationStatuses,
        RequireTransitioning, RequireDestination, RequireIdleNavigation, RequireIdleActivity, RequireNoActiveTarget, RequireActiveTarget,
        MatchResourceCritical, MatchResourceDegraded, RequireDefensivePosture, MinProgressPercent, MaxProgressPercent, MinResourcePercent,
        MaxResourcePercent, MinWarningCount, MaxWarningCount, MinUnknownCount, MaxUnknownCount, MinAvailableCount, MaxAvailableCount,
        MinConfidence, MaxConfidence, MetricName, MinMetricValue, MaxMetricValue, DirectiveKind, Priority, SuggestedPolicy, Blocks,
        Aborts, MinimumWait, ThresholdName, PolicyMode, TargetLabelTemplate, Reason);

public sealed record ResourceUsageRule(
    string RuleName,
    IReadOnlyList<string> MatchLabels,
    PolicyRuleMatchMode LabelMatchMode,
    IReadOnlyList<string> MatchTypes,
    PolicyRuleMatchMode TypeMatchMode,
    IReadOnlyList<string> MatchTags,
    bool RequireAllTags,
    IReadOnlyList<ThreatSeverity> AllowedThreatSeverities,
    ThreatSeverity? MinThreatSeverity,
    RiskSeverity? MinRiskSeverity,
    IReadOnlyList<RiskPolicySuggestion> MatchSuggestedPolicies,
    IReadOnlyList<SessionStatus> MatchSessionStatuses,
    IReadOnlyList<NavigationStatus> MatchNavigationStatuses,
    bool? RequireTransitioning,
    bool RequireDestination,
    bool RequireIdleNavigation,
    bool RequireIdleActivity,
    bool RequireNoActiveTarget,
    bool RequireActiveTarget,
    bool? MatchResourceCritical,
    bool? MatchResourceDegraded,
    bool RequireDefensivePosture,
    double? MinProgressPercent,
    double? MaxProgressPercent,
    double? MinResourcePercent,
    double? MaxResourcePercent,
    int? MinWarningCount,
    int? MaxWarningCount,
    int? MinUnknownCount,
    int? MaxUnknownCount,
    int? MinAvailableCount,
    int? MaxAvailableCount,
    double? MinConfidence,
    double? MaxConfidence,
    string? MetricName,
    double? MinMetricValue,
    double? MaxMetricValue,
    DecisionDirectiveKind DirectiveKind,
    int Priority,
    string SuggestedPolicy,
    bool Blocks,
    bool Aborts,
    TimeSpan MinimumWait,
    string? ThresholdName,
    string? PolicyMode,
    string? TargetLabelTemplate,
    string Reason) : PolicyRule(
        RuleName, PolicyRuleFamily.ResourceUsage, MatchLabels, LabelMatchMode, MatchTypes, TypeMatchMode, MatchTags, RequireAllTags,
        AllowedThreatSeverities, MinThreatSeverity, MinRiskSeverity, MatchSuggestedPolicies, MatchSessionStatuses, MatchNavigationStatuses,
        RequireTransitioning, RequireDestination, RequireIdleNavigation, RequireIdleActivity, RequireNoActiveTarget, RequireActiveTarget,
        MatchResourceCritical, MatchResourceDegraded, RequireDefensivePosture, MinProgressPercent, MaxProgressPercent, MinResourcePercent,
        MaxResourcePercent, MinWarningCount, MaxWarningCount, MinUnknownCount, MaxUnknownCount, MinAvailableCount, MaxAvailableCount,
        MinConfidence, MaxConfidence, MetricName, MinMetricValue, MaxMetricValue, DirectiveKind, Priority, SuggestedPolicy, Blocks,
        Aborts, MinimumWait, ThresholdName, PolicyMode, TargetLabelTemplate, Reason);

public sealed record TransitRule(
    string RuleName,
    IReadOnlyList<string> MatchLabels,
    PolicyRuleMatchMode LabelMatchMode,
    IReadOnlyList<string> MatchTypes,
    PolicyRuleMatchMode TypeMatchMode,
    IReadOnlyList<string> MatchTags,
    bool RequireAllTags,
    IReadOnlyList<ThreatSeverity> AllowedThreatSeverities,
    ThreatSeverity? MinThreatSeverity,
    RiskSeverity? MinRiskSeverity,
    IReadOnlyList<RiskPolicySuggestion> MatchSuggestedPolicies,
    IReadOnlyList<SessionStatus> MatchSessionStatuses,
    IReadOnlyList<NavigationStatus> MatchNavigationStatuses,
    bool? RequireTransitioning,
    bool RequireDestination,
    bool RequireIdleNavigation,
    bool RequireIdleActivity,
    bool RequireNoActiveTarget,
    bool RequireActiveTarget,
    bool? MatchResourceCritical,
    bool? MatchResourceDegraded,
    bool RequireDefensivePosture,
    double? MinProgressPercent,
    double? MaxProgressPercent,
    double? MinResourcePercent,
    double? MaxResourcePercent,
    int? MinWarningCount,
    int? MaxWarningCount,
    int? MinUnknownCount,
    int? MaxUnknownCount,
    int? MinAvailableCount,
    int? MaxAvailableCount,
    double? MinConfidence,
    double? MaxConfidence,
    string? MetricName,
    double? MinMetricValue,
    double? MaxMetricValue,
    DecisionDirectiveKind DirectiveKind,
    int Priority,
    string SuggestedPolicy,
    bool Blocks,
    bool Aborts,
    TimeSpan MinimumWait,
    string? ThresholdName,
    string? PolicyMode,
    string? TargetLabelTemplate,
    string Reason) : PolicyRule(
        RuleName, PolicyRuleFamily.Transit, MatchLabels, LabelMatchMode, MatchTypes, TypeMatchMode, MatchTags, RequireAllTags,
        AllowedThreatSeverities, MinThreatSeverity, MinRiskSeverity, MatchSuggestedPolicies, MatchSessionStatuses, MatchNavigationStatuses,
        RequireTransitioning, RequireDestination, RequireIdleNavigation, RequireIdleActivity, RequireNoActiveTarget, RequireActiveTarget,
        MatchResourceCritical, MatchResourceDegraded, RequireDefensivePosture, MinProgressPercent, MaxProgressPercent, MinResourcePercent,
        MaxResourcePercent, MinWarningCount, MaxWarningCount, MinUnknownCount, MaxUnknownCount, MinAvailableCount, MaxAvailableCount,
        MinConfidence, MaxConfidence, MetricName, MinMetricValue, MaxMetricValue, DirectiveKind, Priority, SuggestedPolicy, Blocks,
        Aborts, MinimumWait, ThresholdName, PolicyMode, TargetLabelTemplate, Reason);

public sealed record AbortRule(
    string RuleName,
    IReadOnlyList<string> MatchLabels,
    PolicyRuleMatchMode LabelMatchMode,
    IReadOnlyList<string> MatchTypes,
    PolicyRuleMatchMode TypeMatchMode,
    IReadOnlyList<string> MatchTags,
    bool RequireAllTags,
    IReadOnlyList<ThreatSeverity> AllowedThreatSeverities,
    ThreatSeverity? MinThreatSeverity,
    RiskSeverity? MinRiskSeverity,
    IReadOnlyList<RiskPolicySuggestion> MatchSuggestedPolicies,
    IReadOnlyList<SessionStatus> MatchSessionStatuses,
    IReadOnlyList<NavigationStatus> MatchNavigationStatuses,
    bool? RequireTransitioning,
    bool RequireDestination,
    bool RequireIdleNavigation,
    bool RequireIdleActivity,
    bool RequireNoActiveTarget,
    bool RequireActiveTarget,
    bool? MatchResourceCritical,
    bool? MatchResourceDegraded,
    bool RequireDefensivePosture,
    double? MinProgressPercent,
    double? MaxProgressPercent,
    double? MinResourcePercent,
    double? MaxResourcePercent,
    int? MinWarningCount,
    int? MaxWarningCount,
    int? MinUnknownCount,
    int? MaxUnknownCount,
    int? MinAvailableCount,
    int? MaxAvailableCount,
    double? MinConfidence,
    double? MaxConfidence,
    string? MetricName,
    double? MinMetricValue,
    double? MaxMetricValue,
    DecisionDirectiveKind DirectiveKind,
    int Priority,
    string SuggestedPolicy,
    bool Blocks,
    bool Aborts,
    TimeSpan MinimumWait,
    string? ThresholdName,
    string? PolicyMode,
    string? TargetLabelTemplate,
    string Reason) : PolicyRule(
        RuleName, PolicyRuleFamily.Abort, MatchLabels, LabelMatchMode, MatchTypes, TypeMatchMode, MatchTags, RequireAllTags,
        AllowedThreatSeverities, MinThreatSeverity, MinRiskSeverity, MatchSuggestedPolicies, MatchSessionStatuses, MatchNavigationStatuses,
        RequireTransitioning, RequireDestination, RequireIdleNavigation, RequireIdleActivity, RequireNoActiveTarget, RequireActiveTarget,
        MatchResourceCritical, MatchResourceDegraded, RequireDefensivePosture, MinProgressPercent, MaxProgressPercent, MinResourcePercent,
        MaxResourcePercent, MinWarningCount, MaxWarningCount, MinUnknownCount, MaxUnknownCount, MinAvailableCount, MaxAvailableCount,
        MinConfidence, MaxConfidence, MetricName, MinMetricValue, MaxMetricValue, DirectiveKind, Priority, SuggestedPolicy, Blocks,
        Aborts, MinimumWait, ThresholdName, PolicyMode, TargetLabelTemplate, Reason);
